/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedIndexRouteImport } from './routes/saved/index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators/index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as SavedDdmRouteImport } from './routes/saved/ddm'
import { Route as SavedChowderRouteImport } from './routes/saved/chowder'
import { Route as CalculatorsSavingsGoalRouteImport } from './routes/calculators/savings-goal'
import { Route as CalculatorsRetirement4percentRouteImport } from './routes/calculators/retirement4percent'
import { Route as CalculatorsRetirementDividendRouteImport } from './routes/calculators/retirement-dividend'
import { Route as CalculatorsCompoundInterestRouteImport } from './routes/calculators/CompoundInterest'
import { Route as AnalysisDdmRouteImport } from './routes/analysis/ddm'
import { Route as AnalysisChowderRouteImport } from './routes/analysis/chowder'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SavedRoute,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalculatorsRoute,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const SavedDdmRoute = SavedDdmRouteImport.update({
  id: '/ddm',
  path: '/ddm',
  getParentRoute: () => SavedRoute,
} as any)
const SavedChowderRoute = SavedChowderRouteImport.update({
  id: '/chowder',
  path: '/chowder',
  getParentRoute: () => SavedRoute,
} as any)
const CalculatorsSavingsGoalRoute = CalculatorsSavingsGoalRouteImport.update({
  id: '/savings-goal',
  path: '/savings-goal',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsRetirement4percentRoute =
  CalculatorsRetirement4percentRouteImport.update({
    id: '/retirement4percent',
    path: '/retirement4percent',
    getParentRoute: () => CalculatorsRoute,
  } as any)
const CalculatorsRetirementDividendRoute =
  CalculatorsRetirementDividendRouteImport.update({
    id: '/retirement-dividend',
    path: '/retirement-dividend',
    getParentRoute: () => CalculatorsRoute,
  } as any)
const CalculatorsCompoundInterestRoute =
  CalculatorsCompoundInterestRouteImport.update({
    id: '/CompoundInterest',
    path: '/CompoundInterest',
    getParentRoute: () => CalculatorsRoute,
  } as any)
const AnalysisDdmRoute = AnalysisDdmRouteImport.update({
  id: '/ddm',
  path: '/ddm',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisChowderRoute = AnalysisChowderRouteImport.update({
  id: '/chowder',
  path: '/chowder',
  getParentRoute: () => AnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/calculators': typeof CalculatorsRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/learn': typeof LearnRoute
  '/saved': typeof SavedRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/analysis/chowder': typeof AnalysisChowderRoute
  '/analysis/ddm': typeof AnalysisDdmRoute
  '/calculators/CompoundInterest': typeof CalculatorsCompoundInterestRoute
  '/calculators/retirement-dividend': typeof CalculatorsRetirementDividendRoute
  '/calculators/retirement4percent': typeof CalculatorsRetirement4percentRoute
  '/calculators/savings-goal': typeof CalculatorsSavingsGoalRoute
  '/saved/chowder': typeof SavedChowderRoute
  '/saved/ddm': typeof SavedDdmRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/saved/': typeof SavedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/analysis/chowder': typeof AnalysisChowderRoute
  '/analysis/ddm': typeof AnalysisDdmRoute
  '/calculators/CompoundInterest': typeof CalculatorsCompoundInterestRoute
  '/calculators/retirement-dividend': typeof CalculatorsRetirementDividendRoute
  '/calculators/retirement4percent': typeof CalculatorsRetirement4percentRoute
  '/calculators/savings-goal': typeof CalculatorsSavingsGoalRoute
  '/saved/chowder': typeof SavedChowderRoute
  '/saved/ddm': typeof SavedDdmRoute
  '/analysis': typeof AnalysisIndexRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/saved': typeof SavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/calculators': typeof CalculatorsRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/learn': typeof LearnRoute
  '/saved': typeof SavedRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/analysis/chowder': typeof AnalysisChowderRoute
  '/analysis/ddm': typeof AnalysisDdmRoute
  '/calculators/CompoundInterest': typeof CalculatorsCompoundInterestRoute
  '/calculators/retirement-dividend': typeof CalculatorsRetirementDividendRoute
  '/calculators/retirement4percent': typeof CalculatorsRetirement4percentRoute
  '/calculators/savings-goal': typeof CalculatorsSavingsGoalRoute
  '/saved/chowder': typeof SavedChowderRoute
  '/saved/ddm': typeof SavedDdmRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/saved/': typeof SavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/calculators'
    | '/companies'
    | '/learn'
    | '/saved'
    | '/settings'
    | '/sign-in'
    | '/analysis/chowder'
    | '/analysis/ddm'
    | '/calculators/CompoundInterest'
    | '/calculators/retirement-dividend'
    | '/calculators/retirement4percent'
    | '/calculators/savings-goal'
    | '/saved/chowder'
    | '/saved/ddm'
    | '/analysis/'
    | '/calculators/'
    | '/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/learn'
    | '/settings'
    | '/sign-in'
    | '/analysis/chowder'
    | '/analysis/ddm'
    | '/calculators/CompoundInterest'
    | '/calculators/retirement-dividend'
    | '/calculators/retirement4percent'
    | '/calculators/savings-goal'
    | '/saved/chowder'
    | '/saved/ddm'
    | '/analysis'
    | '/calculators'
    | '/saved'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/calculators'
    | '/companies'
    | '/learn'
    | '/saved'
    | '/settings'
    | '/sign-in'
    | '/analysis/chowder'
    | '/analysis/ddm'
    | '/calculators/CompoundInterest'
    | '/calculators/retirement-dividend'
    | '/calculators/retirement4percent'
    | '/calculators/savings-goal'
    | '/saved/chowder'
    | '/saved/ddm'
    | '/analysis/'
    | '/calculators/'
    | '/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  CompaniesRoute: typeof CompaniesRoute
  LearnRoute: typeof LearnRoute
  SavedRoute: typeof SavedRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/'
      fullPath: '/saved/'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof SavedRoute
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/saved/ddm': {
      id: '/saved/ddm'
      path: '/ddm'
      fullPath: '/saved/ddm'
      preLoaderRoute: typeof SavedDdmRouteImport
      parentRoute: typeof SavedRoute
    }
    '/saved/chowder': {
      id: '/saved/chowder'
      path: '/chowder'
      fullPath: '/saved/chowder'
      preLoaderRoute: typeof SavedChowderRouteImport
      parentRoute: typeof SavedRoute
    }
    '/calculators/savings-goal': {
      id: '/calculators/savings-goal'
      path: '/savings-goal'
      fullPath: '/calculators/savings-goal'
      preLoaderRoute: typeof CalculatorsSavingsGoalRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/retirement4percent': {
      id: '/calculators/retirement4percent'
      path: '/retirement4percent'
      fullPath: '/calculators/retirement4percent'
      preLoaderRoute: typeof CalculatorsRetirement4percentRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/retirement-dividend': {
      id: '/calculators/retirement-dividend'
      path: '/retirement-dividend'
      fullPath: '/calculators/retirement-dividend'
      preLoaderRoute: typeof CalculatorsRetirementDividendRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/CompoundInterest': {
      id: '/calculators/CompoundInterest'
      path: '/CompoundInterest'
      fullPath: '/calculators/CompoundInterest'
      preLoaderRoute: typeof CalculatorsCompoundInterestRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/analysis/ddm': {
      id: '/analysis/ddm'
      path: '/ddm'
      fullPath: '/analysis/ddm'
      preLoaderRoute: typeof AnalysisDdmRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/chowder': {
      id: '/analysis/chowder'
      path: '/chowder'
      fullPath: '/analysis/chowder'
      preLoaderRoute: typeof AnalysisChowderRouteImport
      parentRoute: typeof AnalysisRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisChowderRoute: typeof AnalysisChowderRoute
  AnalysisDdmRoute: typeof AnalysisDdmRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisChowderRoute: AnalysisChowderRoute,
  AnalysisDdmRoute: AnalysisDdmRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface CalculatorsRouteChildren {
  CalculatorsCompoundInterestRoute: typeof CalculatorsCompoundInterestRoute
  CalculatorsRetirementDividendRoute: typeof CalculatorsRetirementDividendRoute
  CalculatorsRetirement4percentRoute: typeof CalculatorsRetirement4percentRoute
  CalculatorsSavingsGoalRoute: typeof CalculatorsSavingsGoalRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsCompoundInterestRoute: CalculatorsCompoundInterestRoute,
  CalculatorsRetirementDividendRoute: CalculatorsRetirementDividendRoute,
  CalculatorsRetirement4percentRoute: CalculatorsRetirement4percentRoute,
  CalculatorsSavingsGoalRoute: CalculatorsSavingsGoalRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

interface SavedRouteChildren {
  SavedChowderRoute: typeof SavedChowderRoute
  SavedDdmRoute: typeof SavedDdmRoute
  SavedIndexRoute: typeof SavedIndexRoute
}

const SavedRouteChildren: SavedRouteChildren = {
  SavedChowderRoute: SavedChowderRoute,
  SavedDdmRoute: SavedDdmRoute,
  SavedIndexRoute: SavedIndexRoute,
}

const SavedRouteWithChildren = SavedRoute._addFileChildren(SavedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  CompaniesRoute: CompaniesRoute,
  LearnRoute: LearnRoute,
  SavedRoute: SavedRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
