# Custom application configuration (CORS)
app:
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000

# Spring Boot standard configuration (database, JPA)
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/invested}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true