spring:
  application:
    name: backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/invested}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
# Finnhub API Configuration
# Load FINNHUB_API_KEY from environment variable
# Make sure to set FINNHUB_API_KEY in your .env file or environment

# ⚠️  SECURITY CHECKLIST FOR PRODUCTION DEPLOYMENT ⚠️
# Before deploying to production, ensure you have:
# 1. Proper authentication and authorization configured in SecurityConfig.java
# 2. HTTPS enabled (not HTTP)
# 3. CORS configured for your specific frontend domain
# 4. Rate limiting implemented
# 5. API endpoints protected with proper authentication
# 6. Environment variables secured (not in code)
# 7. Database credentials secured
# 8. Logging configured to not expose sensitive data
# 9. Security headers configured (HSTS, CSP, etc.)
# 10. Regular security updates and dependency scanning
